# Generated by Django 5.2.2 on 2025-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('membership_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
